package com.kapirti.social_chat_food_video.model

import com.kapirti.social_chat_food_video.core.constants.ConsGender.FEMALE
import com.kapirti.social_chat_food_video.core.constants.ConsGender.MALE
import com.kapirti.social_chat_food_video.core.constants.Hobby.DANCE
import com.kapirti.social_chat_food_video.core.constants.Hobby.READ
import com.kapirti.social_chat_food_video.core.constants.Hobby.PLAY_GAMES
import com.kapirti.social_chat_food_video.core.constants.Hobby.DRAW
import com.kapirti.social_chat_food_video.core.constants.Hobby.WATCH_MOVIES
import com.kapirti.social_chat_food_video.core.constants.Hobby.WORK_OUT
import com.kapirti.social_chat_food_video.core.constants.SelectType.FLIRT
import com.kapirti.social_chat_food_video.core.constants.SelectType.HOTEL
import com.kapirti.social_chat_food_video.core.constants.SelectType.LANGUAGE_PRACTICE
import com.kapirti.social_chat_food_video.core.constants.SelectType.MARRIAGE
import com.kapirti.social_chat_food_video.core.constants.SelectType.RESTAURANT
import com.kapirti.social_chat_food_video.core.constants.ConstLanguage
import com.kapirti.social_chat_food_video.core.constants.CountryConst
import com.kapirti.social_chat_food_video.R.string as AppText
import com.kapirti.social_chat_food_video.core.constants.SelectType.CAFE

object LuccaRepo {
    fun getSelectType(): List<String> = selectTypes
    fun getGender(): List<String> = genders
    fun getHobbies(): List<String> = hobbies
    fun getCountries() : List<CountryFlag> = countries
    fun getLanguages(): List<String> = languages
}

private val selectTypes = listOf(MARRIAGE, FLIRT, LANGUAGE_PRACTICE, HOTEL, RESTAURANT, CAFE)
private val genders = listOf(MALE, FEMALE)
private val hobbies = listOf(READ, WORK_OUT, DRAW, PLAY_GAMES, DANCE, WATCH_MOVIES)

private val languages = listOf(
    ConstLanguage.ABKHAZIAN,
    ConstLanguage.AFAR,
    ConstLanguage.AFRIKAANS,
    ConstLanguage.AKAN,
    ConstLanguage.ALBANIAN,
    ConstLanguage.AMHARIC,
    ConstLanguage.ARABIC,
    ConstLanguage.ARAGONESE,
    ConstLanguage.ARMENIAN,
    ConstLanguage.ASSAMESE,
    ConstLanguage.AVARIC,
    ConstLanguage.AVESTAN,
    ConstLanguage.AYMARA,
    ConstLanguage.AZERBAIJANI,
    ConstLanguage.BAMBARA,
    ConstLanguage.BANGLA,
    ConstLanguage.BASHKIR,
    ConstLanguage.BASQUE,
    ConstLanguage.BELARUSIAN,
    ConstLanguage.BH,
    ConstLanguage.BISLAMA,
    ConstLanguage.BOSNIAN,
    ConstLanguage.BRETON,
    ConstLanguage.BULGARIAN,
    ConstLanguage.BURMESE,
    ConstLanguage.CATALAN,
    ConstLanguage.CHAMORRO,
    ConstLanguage.CHECHEN,
    ConstLanguage.CHINESE,
    ConstLanguage.CHURCH_SLAVIC,
    ConstLanguage.CHUVASH,
    ConstLanguage.CORNISH,
    ConstLanguage.CORSICAN,
    ConstLanguage.CREE,
    ConstLanguage.CROATIAN,
    ConstLanguage.CZECH,
    ConstLanguage.DANISH,
    ConstLanguage.DIVEHI,
    ConstLanguage.DUTCH,
    ConstLanguage.DZONGKHA,
    ConstLanguage.ENGLISH,
    ConstLanguage.ESPERANTO,
    ConstLanguage.ESTONIAN,
    ConstLanguage.EWE,
    ConstLanguage.FAROESE,
    ConstLanguage.FIJIAN,
    ConstLanguage.FINNISH,
    ConstLanguage.FRENCH,
    ConstLanguage.FULAH,
    ConstLanguage.GALICIAN,
    ConstLanguage.GANDA,
    ConstLanguage.GEORGIAN,
    ConstLanguage.GERMAN,
    ConstLanguage.GREEK,
    ConstLanguage.GUARANI,
    ConstLanguage.GUJARATI,
    ConstLanguage.HAITIAN_GREOLE,
    ConstLanguage.HAUSA,
    ConstLanguage.HEBREW,
    ConstLanguage.HERERO,
    ConstLanguage.HINDI,
    ConstLanguage.HIRI_MOTU,
    ConstLanguage.HUNGARIAN,
    ConstLanguage.IDO,
    ConstLanguage.IGBO,
    ConstLanguage.INDONESIAN,
    ConstLanguage.INTERLINGUA,
    ConstLanguage.INUKTITUT,
    ConstLanguage.INUPIAQ,
    ConstLanguage.IRISH,
    ConstLanguage.ITALIAN,
    ConstLanguage.JAPANESE,
    ConstLanguage.JAVANESE,
    ConstLanguage.KALAALLISUT,
    ConstLanguage.KANNADA,
    ConstLanguage.KANURI,
    ConstLanguage.KASHMIRI,
    ConstLanguage.KAZAKH,
    ConstLanguage.KHMER,
    ConstLanguage.KIKUYU,
    ConstLanguage.KINYARWANDA,
    ConstLanguage.KOMI,
    ConstLanguage.KONGO,
    ConstLanguage.KOREAN,
    ConstLanguage.KUANYAMA,
    ConstLanguage.KURDISH,
    ConstLanguage.KYRGYZ,
    ConstLanguage.LAO,
    ConstLanguage.LATIN,
    ConstLanguage.LATVIAN,
    ConstLanguage.LIMBURGISH,
    ConstLanguage.LINGALA,
    ConstLanguage.LITHUANIAN,
    ConstLanguage.LUBA_KATANGA,
    ConstLanguage.LUXEMBOURGISH,
    ConstLanguage.MACEDONIAN,
    ConstLanguage.MALAGASY,
    ConstLanguage.MALAY,
    ConstLanguage.MALAYALAM,
    ConstLanguage.MALTESE,
    ConstLanguage.MANX,
    ConstLanguage.MAORI,
    ConstLanguage.MARATHI,
    ConstLanguage.MARSHALLESE,
    ConstLanguage.MONGOLIAN,
    ConstLanguage.NAURU,
    ConstLanguage.NAVAJO,
    ConstLanguage.NDONGA,
    ConstLanguage.NEPALI,
    ConstLanguage.NORTH_NDEBELE,
    ConstLanguage.NORTHERN_SAMI,
    ConstLanguage.NORWEGIAN,
    ConstLanguage.NYANJA,
    ConstLanguage.OCCITAN,
    ConstLanguage.OJIBWA,
    ConstLanguage.ORIYA,
    ConstLanguage.OROMO,
    ConstLanguage.OSSETIC,
    ConstLanguage.PALI,
    ConstLanguage.PASHTO,
    ConstLanguage.PERSIAN,
    ConstLanguage.POLISH,
    ConstLanguage.PORTUGUESE,
    ConstLanguage.PUNJABI,
    ConstLanguage.QUECHUA,
    ConstLanguage.ROMANIAN,
    ConstLanguage.RUNDI,
    ConstLanguage.RUSSIAN,
    ConstLanguage.SAMOAN,
    ConstLanguage.SANGO,
    ConstLanguage.SANSKRIT,
    ConstLanguage.SARDINIAN,
    ConstLanguage.SERBIAN,
    ConstLanguage.SHONA,
    ConstLanguage.SINDHI,
    ConstLanguage.SINHALA,
    ConstLanguage.SLOVAK,
    ConstLanguage.SLOVENIAN,
    ConstLanguage.SOMALI,
    ConstLanguage.SPANISH,
    ConstLanguage.SWAHILI,
    ConstLanguage.SWATI,
    ConstLanguage.SWEDISH,
    ConstLanguage.TAGALOG,
    ConstLanguage.TAHITIAN,
    ConstLanguage.TAJIK,
    ConstLanguage.TAMIL,
    ConstLanguage.TATAR,
    ConstLanguage.TELUGU,
    ConstLanguage.THAI,
    ConstLanguage.TIBETAN,
    ConstLanguage.TIGRINYA,
    ConstLanguage.TONGAN,
    ConstLanguage.TSONGA,
    ConstLanguage.TSWANA,
    ConstLanguage.TURKISH,
    ConstLanguage.TURKMEN,
    ConstLanguage.TWI,
    ConstLanguage.UKRAINIAN,
    ConstLanguage.URDU,
    ConstLanguage.UYGHUR,
    ConstLanguage.UZBEK,
    ConstLanguage.VENDA,
    ConstLanguage.VIETNAMESE,
    ConstLanguage.VOLAPUK,
    ConstLanguage.WALLOON,
    ConstLanguage.WELSH,
    ConstLanguage.WOLOF,
    ConstLanguage.XHOSA,
    ConstLanguage.YIDDISH,
    ConstLanguage.YORUBA,
    ConstLanguage.ZHUANG,
    ConstLanguage.ZULU
)


private val countries = listOf(
    CountryFlag(CountryConst.CC_ALBANIA, AppText.cc_albania, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Falbania.png?alt=media&token=39ccc9c0-9ce8-4aed-ba3c-c2f39d161cd1"),
    CountryFlag(CountryConst.CC_ALGERIA, AppText.cc_algeria, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Falgeria.png?alt=media&token=f806b175-a1a1-4699-a049-d001c84b75eb"),
    CountryFlag(CountryConst.CC_ANGOLA, AppText.cc_angola, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fangola.png?alt=media&token=d66c8b71-c73a-4ff7-91a6-6bce064ed32e"),
    CountryFlag(CountryConst.CC_ANTIGUA_BARBUDA, AppText.cc_antigua_and_barbuda, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fantigua_and_barbuda.png?alt=media&token=452075b2-9e8b-4954-bd09-ff39d49fd2a1"),
    CountryFlag(CountryConst.CC_ARGENTINA, AppText.cc_argentina, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fargentina.png?alt=media&token=5c70ddb9-8e43-4317-8c20-5037c6155319"),
    CountryFlag(CountryConst.CC_ARMENIA, AppText.cc_armenia, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Farmenia.png?alt=media&token=4eb39338-6952-4805-a0fd-c26a68de1f54"),
    CountryFlag(CountryConst.CC_ARUBA, AppText.cc_aruba, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Faruba.png?alt=media&token=af918265-b436-460d-9eb5-076558f6c10e"),
    CountryFlag(CountryConst.CC_AUSTRALIA, AppText.cc_australia, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Faustralia.png?alt=media&token=6e2395f8-0996-4831-b482-b0f134edf6e5"),
    CountryFlag(CountryConst.CC_AUSTRIA, AppText.cc_austria, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Faustria.png?alt=media&token=2af94254-abc7-44db-806d-36a2e8bacf8e"),
    CountryFlag(CountryConst.CC_AZERBAIJAN, AppText.cc_azerbaijan, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fazerbaijan.png?alt=media&token=ee03d17d-37ff-4091-9619-dc27856d44a4"),
    CountryFlag(CountryConst.CC_BAHAMAS, AppText.cc_bahamas, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fbahamas.png?alt=media&token=ee11a23d-1ff1-46fc-b862-fcfe343b204a"),
    CountryFlag(CountryConst.CC_BAHRAIN, AppText.cc_bahrain, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fbahrain.png?alt=media&token=d2431d99-b5da-4cc0-9a61-54f9ef9893fb"),
    CountryFlag(CountryConst.CC_BANGLADESH, AppText.cc_bangladesh, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fbangladesh.png?alt=media&token=17121d96-fddd-4137-a139-f2d35874e6df"),
    CountryFlag(CountryConst.CC_BELARUS, AppText.cc_belarus, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fbelarus.png?alt=media&token=05bba0e0-b779-40b8-8af6-4d7ff412be5d"),
    CountryFlag(CountryConst.CC_BELGIUM, AppText.cc_belgium, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fbelgium.png?alt=media&token=cb0a4ec6-4879-4650-9d68-7a9f037a69db"),
    CountryFlag(CountryConst.CC_BELIZE, AppText.cc_belize, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fbelize.png?alt=media&token=d5eabddb-f535-4874-847f-6ab4a2ec049b"),
    CountryFlag(CountryConst.CC_BENIN, AppText.cc_benin, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fbenin.png?alt=media&token=d2a679ad-fd04-45f4-a209-e98ce730ff16"),
    CountryFlag(CountryConst.CC_BERMUDA, AppText.cc_bermuda, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fbermuda.png?alt=media&token=c773775e-057a-4df5-9492-a7a41c3f5f16"),
    CountryFlag(CountryConst.CC_BOLIVIA, AppText.cc_bolivia, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fbolivia.png?alt=media&token=2a4555bf-25fe-4b88-b341-e2d6ed0a48cc"),
    CountryFlag(CountryConst.CC_BOSNIA_HERZEGOVINA, AppText.cc_bosnia_and_herzegovina, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fbosnia_and_herzegovina.png?alt=media&token=57ebb894-628b-47d2-a292-c236df8e0450"),
    CountryFlag(CountryConst.CC_BOTSWANA, AppText.cc_botswana, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fbotswana.png?alt=media&token=62626cc9-7141-48b6-946a-d0eb710a364f"),
    CountryFlag(CountryConst.CC_BRAZIL, AppText.cc_brazil, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fbrazil.png?alt=media&token=1074c1b9-3724-4bf5-a466-f5d0de2e31f0"),
    CountryFlag(CountryConst.CC_BRITISH_VIRGIN_ISLANDS, AppText.cc_british_virgin_islands, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fbritish_virgin_islands.png?alt=media&token=94cdd420-8203-488f-b19b-679ae9ac1804"),
    CountryFlag(CountryConst.CC_BULGARIA, AppText.cc_bulgaria, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fbulgaria.png?alt=media&token=660450f5-217d-4b7c-b16d-6c9aad3b1ac0"),
    CountryFlag(CountryConst.CC_BURKINA_FASO, AppText.cc_burkina_faso, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fburkina_faso.png?alt=media&token=54f304ae-d2a1-4ad5-b606-881da41d5967"),
    CountryFlag(CountryConst.CC_CAMBODIA, AppText.cc_cambodia, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fcambodia.png?alt=media&token=587143f2-e117-4421-906b-29639319a31b"),
    CountryFlag(CountryConst.CC_CAMEROON, AppText.cc_cameroon, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fcameroon.png?alt=media&token=3670d4d4-799f-4bc3-b13d-ae83c38ef2ec"),
    CountryFlag(CountryConst.CC_CANADA, AppText.cc_canada, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fcanada.png?alt=media&token=34b05f09-f60d-4fc1-a694-0856400c3e13"),
    CountryFlag(CountryConst.CC_CAPE_VERDE, AppText.cc_cape_verde, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fcape_verde.png?alt=media&token=5b7d91b0-f2b3-45a1-8506-846516dd625e"),
    CountryFlag(CountryConst.CC_CAYMAN_ISLANDS, AppText.cc_cayman_islands, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fcayman_islands.png?alt=media&token=be4e4886-8f40-4341-8434-30cc7dde0abe"),
    CountryFlag(CountryConst.CC_CHAD, AppText.cc_chad, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fchad.png?alt=media&token=2fcaccab-8df0-4221-a40b-bd36b93519ca"),
    CountryFlag(CountryConst.CC_CHILE, AppText.cc_chile, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fchile.png?alt=media&token=a568b876-2e71-413b-bcc0-708b1adc7ff2"),
    CountryFlag(CountryConst.CC_CHINA, AppText.cc_china, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fchina.png?alt=media&token=23ba305c-b718-4916-aed0-b5f87bc55182"),
    CountryFlag(CountryConst.CC_COLOMBIA, AppText.cc_colombia, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fcolombia.png?alt=media&token=34f9ea1b-53f1-4f39-bab7-87ec181f0c34"),
    CountryFlag(CountryConst.CC_COMOROS, AppText.cc_comoros, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fcomoros.png?alt=media&token=ff42d827-a489-4a9c-a763-d6850a577954"),
    CountryFlag(CountryConst.CC_CONGO_BRAZZAVILLE, AppText.cc_congo_brazzaville, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fcongo_brazzaville.png?alt=media&token=93ae57cd-853f-4dfa-a62e-49772875b36a"),
    CountryFlag(CountryConst.CC_CONGO_KINSHASA, AppText.cc_congo_kinshasa, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fcongo_kinshasa.png?alt=media&token=3550577d-dd87-49b2-80ac-9e321eb2acfa"),
    CountryFlag(CountryConst.CC_COSTA_RICA, AppText.cc_costa_rica, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fcosta_rica.png?alt=media&token=6af73726-fd8a-4333-8653-e14025fe070e"),
    CountryFlag(CountryConst.CC_CROATIA, AppText.cc_croatia, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fcroatia.png?alt=media&token=70dfc595-ca6d-4b91-9a04-a065138ccbfd"),
    CountryFlag(CountryConst.CC_CUBA, AppText.cc_cuba, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fcuba.png?alt=media&token=2ad22f22-45fd-4f82-a1af-4207aa1a98e8"),
    CountryFlag(CountryConst.CC_CURACAO, AppText.cc_curacao, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fcuracao.png?alt=media&token=24637ef8-bfb5-4529-81af-55758628e01f"),
    CountryFlag(CountryConst.CC_CYPRUS, AppText.cc_cyprus, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fcyprus.png?alt=media&token=67abe86d-4a2c-484c-b8f7-a44ccf6904df"),
    CountryFlag(CountryConst.CC_CZECHIA, AppText.cc_czechia, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fczech.png?alt=media&token=ba48a1b8-346b-4687-835c-a830d92a0784"),
    CountryFlag(CountryConst.CC_COTE_D_IVOIRE, AppText.cc_cote_d_ivoire, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fivory_coast.png?alt=media&token=8d55c908-fa54-4b83-9d48-12581118942b"),
    CountryFlag(CountryConst.CC_DENMARK, AppText.cc_denmark, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fdenmark.png?alt=media&token=ce78f3fc-eecc-4c2e-be02-be044633a9fc"),
    CountryFlag(CountryConst.CC_DIJIBOUTI, AppText.cc_dijibuti, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fdjibouti.png?alt=media&token=97103986-a48a-48fb-a5a8-5c6d4e3f73b4"),
    CountryFlag(CountryConst.CC_DOMINICA, AppText.cc_dominica, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fdominica.png?alt=media&token=43344f32-aeb4-4e13-b6bd-4e53151e9085"),
    CountryFlag(CountryConst.CC_DOMINICAN_REPUBLIC, AppText.cc_dominican_republic, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fdominican_republic.png?alt=media&token=2c6eed30-41be-44e1-bdb6-8a9df4a372ee"),
    CountryFlag(CountryConst.CC_ECUADOR, AppText.cc_ecuador, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fecuador.png?alt=media&token=0d2e0fb4-8dc1-4a9b-8e2c-cf0d4b81032e"),
    CountryFlag(CountryConst.CC_EGYPT, AppText.cc_egypt, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fegypt.png?alt=media&token=638aec41-277d-4542-8994-228e07eae5ac"),
    CountryFlag(CountryConst.CC_EL_SALVADOR, AppText.cc_el_salvador, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fel_salvador.png?alt=media&token=ca89c069-2f91-43e8-b4fc-621f78b83100"),
    CountryFlag(CountryConst.CC_ERITREA, AppText.cc_eritrea, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Feritrea.png?alt=media&token=81091c82-38c4-4d5a-acd4-5ea5dfaa11da"),
    CountryFlag(CountryConst.CC_ESTONIA, AppText.cc_estonia, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Festonia.png?alt=media&token=325762a9-0e34-4834-9c40-077b79e147d2"),
    CountryFlag(CountryConst.CC_FIJI, AppText.cc_fiji, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Ffiji.png?alt=media&token=73cdbfd0-ae53-4b67-baaa-6daddc0c57c1"),
    CountryFlag(CountryConst.CC_FINLAND, AppText.cc_finland, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Ffinland.png?alt=media&token=2ccc763c-eb83-4367-ac68-3bdc87a91f05"),
    CountryFlag(CountryConst.CC_FRANCE, AppText.cc_france, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Ffrance.png?alt=media&token=dbd5efdb-cf67-4052-9565-2e63381956a0"),
    CountryFlag(CountryConst.CC_GABON, AppText.cc_gabon, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fgabon.png?alt=media&token=8432ac1c-810a-4f0f-bb2e-78f8eaf09402"),
    CountryFlag(CountryConst.CC_GAMBIA, AppText.cc_gambia, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fgambia.png?alt=media&token=ca93ba27-f352-4c1d-9444-a657829d1bea"),
    CountryFlag(CountryConst.CC_GEORGIA, AppText.cc_georgia, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fgeorgia.png?alt=media&token=e87ee10b-4f5b-4e1f-98ae-a7c9b4c0c4c4"),
    CountryFlag(CountryConst.CC_GERMANY, AppText.cc_germany, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fgermany.png?alt=media&token=cde382d2-9fd5-45bc-98fa-57754db7171f"),
    CountryFlag(CountryConst.CC_GHANA, AppText.cc_ghana, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fghana.png?alt=media&token=0a709d46-25f4-4e1f-b42a-5ec7c2db4011"),
    CountryFlag(CountryConst.CC_GIBRALTAR, AppText.cc_gibraltar, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fgibraltar.png?alt=media&token=d6de8ed5-5be3-46d9-b3a9-858e71fb5677"),
    CountryFlag(CountryConst.CC_GREECE, AppText.cc_greece, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fgreece.png?alt=media&token=7bbf9a3f-98ae-49bb-95b4-aa971d7ac233"),
    CountryFlag(CountryConst.CC_GRENADA, AppText.cc_grenada, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fgrenada.png?alt=media&token=607edf63-272c-4d58-906e-12882c5fab9c"),
    CountryFlag(CountryConst.CC_GUATEMALA, AppText.cc_guatemala, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fguatemala.png?alt=media&token=7a95aaac-64d6-4613-9e66-75c4bce85af2"),
    CountryFlag(CountryConst.CC_GUINEA, AppText.cc_guinea, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fguinea.png?alt=media&token=528698df-b8e0-4844-b444-2c4d97962527"),
    CountryFlag(CountryConst.CC_GUINEA_BISSAU, AppText.cc_guinea_bissau, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fguinea_bissau.png?alt=media&token=28b3e4ef-cd38-42a5-9ce5-6516cfbca24d"),
    CountryFlag(CountryConst.CC_HAITI, AppText.cc_haiti, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fhaiti.png?alt=media&token=70df66d7-75cb-4232-bdd0-efaaf153cdee"),
    CountryFlag(CountryConst.CC_HONDURAS, AppText.cc_honduras, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fhonduras.png?alt=media&token=caf4157d-d983-4655-9045-090d858d2eb2"),
    CountryFlag(CountryConst.CC_HONG_KONG, AppText.cc_hong_kong, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fhong_kong.png?alt=media&token=be9ce594-8cab-46ff-85de-5005f08cbcdf"),
    CountryFlag(CountryConst.CC_HUNGARY, AppText.cc_hungary, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fhungary.png?alt=media&token=23694f0f-27b4-4754-b8b4-86b6973fbbed"),
    CountryFlag(CountryConst.CC_ICELAND, AppText.cc_iceland, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Ficeland.png?alt=media&token=caba5b89-c4f8-4a7e-8d37-663e1fede770"),
    CountryFlag(CountryConst.CC_INDIA, AppText.cc_india, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Findia.png?alt=media&token=1c7d3e38-8a8c-41ce-ab6f-02f81159410b"),
    CountryFlag(CountryConst.CC_INDONESIA, AppText.cc_indonesia, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Findonesia.png?alt=media&token=203618f8-d9c4-4e7b-af6f-7aa8fad3363f"),
    CountryFlag(CountryConst.CC_IRAN, AppText.cc_iran, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Firan.png?alt=media&token=9285c35a-6bb4-43dc-a213-624b970a12ab"),
    CountryFlag(CountryConst.CC_IRAQ, AppText.cc_iraq, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Firaq.png?alt=media&token=3d2655b0-8ee0-45c7-9086-2f4006f71f64"),
    CountryFlag(CountryConst.CC_IRELAND, AppText.cc_ireland, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fireland.png?alt=media&token=9657a0bf-f4be-47c3-a560-3a7e58c03674"),
    CountryFlag(CountryConst.CC_ISRAEL, AppText.cc_israel, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fisrael.png?alt=media&token=d1cc6178-a421-4a16-a73e-0d6135f5e594"),
    CountryFlag(CountryConst.CC_ITALY, AppText.cc_italy, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fitaly.png?alt=media&token=010a9747-84d5-4e21-91d4-f719674a9559"),
    CountryFlag(CountryConst.CC_JAMAICA, AppText.cc_jamaica, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fjamaica.png?alt=media&token=44ccff41-4607-4606-972f-2122f8ce8224"),
    CountryFlag(CountryConst.CC_JAPAN, AppText.cc_japan, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fjapan.png?alt=media&token=4437ab8d-4e89-4e47-90e4-fccad7edd5b8"),
    CountryFlag(CountryConst.CC_JORDAN, AppText.cc_jordan, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fjordan.png?alt=media&token=85cbf75a-a00f-4166-80ff-77d74c4d180e"),
    CountryFlag(CountryConst.CC_KAZAKHSTAN, AppText.cc_kazakhstan, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fkazakhstan.png?alt=media&token=e70e1e28-6016-4f2f-a27e-f4e263a707c6"),
    CountryFlag(CountryConst.CC_KENYA, AppText.cc_kenya, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fkenya.png?alt=media&token=54d9b408-118f-4487-8271-980b536e63a4"),
    CountryFlag(CountryConst.CC_KUWAIT, AppText.cc_kuwait, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fkuwait.png?alt=media&token=6d60ccbe-6ba7-4ee0-a613-0a4476e95638"),
    CountryFlag(CountryConst.CC_KYRGYZSTAN, AppText.cc_kyrgyzstan, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fkyrgyzstan.png?alt=media&token=1da8af23-6c4e-4757-b858-000d3003f5f6"),
    CountryFlag(CountryConst.CC_LAOS, AppText.cc_laos, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Flaos.png?alt=media&token=adc65700-b8a1-4861-8452-1cc691b8606c"),
    CountryFlag(CountryConst.CC_LATVIA, AppText.cc_latvia, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Flatvia.png?alt=media&token=eb183ae1-9863-4e48-821c-b500cc7ebe2d"),
    CountryFlag(CountryConst.CC_LEBANON, AppText.cc_lebanon, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Flebanon.png?alt=media&token=1af63631-c023-4c88-88d3-f9a37f636edf"),
    CountryFlag(CountryConst.CC_LIBERIA, AppText.cc_liberia, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fliberia.png?alt=media&token=0671898d-306e-4a04-af58-93318852908a"),
    CountryFlag(CountryConst.CC_LIBYA, AppText.cc_libya, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Flibya.png?alt=media&token=0a85dcd5-caab-48c5-9b12-af75bbfa5341"),
    CountryFlag(CountryConst.CC_LIECHTENSTEIN, AppText.cc_liechtenstein, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fliechtenstein.png?alt=media&token=446fed23-9d7f-40de-8cea-f600475f3ecf"),
    CountryFlag(CountryConst.CC_LITHUANIA, AppText.cc_lithuania, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Flithuania.png?alt=media&token=ef99bd69-805c-4f15-b6d4-bc38fe0b0097"),
    CountryFlag(CountryConst.CC_LUXEMBOURG, AppText.cc_luxembourg, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fluxembourg.png?alt=media&token=eb436aaf-b5a9-4fa9-b2e2-ceba11079dca"),
    CountryFlag(CountryConst.CC_MACAO, AppText.cc_macao, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fmacao.png?alt=media&token=32c671da-3632-45b3-bf27-1fb41d5aafd2"),
    CountryFlag(CountryConst.CC_MALAYSIA, AppText.cc_malaysia, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fmalaysia.png?alt=media&token=80cfca30-4f01-4e2b-9953-c3622d51f5c5"),
    CountryFlag(CountryConst.CC_MALDIVES, AppText.cc_maldives, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fmaldives.png?alt=media&token=1e0e2274-d675-4b0d-b754-019f6609725a"),
    CountryFlag(CountryConst.CC_MALI, AppText.cc_mali, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fmali.png?alt=media&token=91b28d5a-9e98-4614-9d2a-c65b3e5c2735"),
    CountryFlag(CountryConst.CC_MALTA, AppText.cc_malta, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fmalta.png?alt=media&token=b2d821c3-96ef-4989-a5cd-522d58f1274c"),
    CountryFlag(CountryConst.CC_MAURITIUS, AppText.cc_mauritius, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fmauritius.png?alt=media&token=883703d1-654a-4b6c-a8f8-46fa9641f028"),
    CountryFlag(CountryConst.CC_MEXICO, AppText.cc_mexico, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fmexico.png?alt=media&token=3123cd98-065c-4a7d-990f-10ccf1aeaedc"),
    CountryFlag(CountryConst.CC_MICRONESIA, AppText.cc_micronesia, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fmicronesia.png?alt=media&token=99df997b-d1db-4337-8dd6-0cee864c5f7b"),
    CountryFlag(CountryConst.CC_MOLDOVA, AppText.cc_moldova, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fmoldova.png?alt=media&token=aa6feecc-9a34-4a2b-83ab-6b67c2041952"),
    CountryFlag(CountryConst.CC_MONACO, AppText.cc_monaco, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fmonaco.png?alt=media&token=1185ccf6-a183-4c2f-82b6-8cf46885a385"),
    CountryFlag(CountryConst.CC_MOROCCO, AppText.cc_morocco, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fmorocco.png?alt=media&token=1c0dd24c-65b6-46c0-9fd8-3bbd19f7ad65"),
    CountryFlag(CountryConst.CC_MOZAMBIQUE, AppText.cc_mozambique, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fmozambique.png?alt=media&token=c464c4f4-58c2-4b0a-a2d9-38523e2634dd"),
    CountryFlag(CountryConst.CC_MYANMAR, AppText.cc_myanmar, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fmyanmar.png?alt=media&token=f7127d6e-5527-45c8-89cc-94eb5a3b8874"),
    CountryFlag(CountryConst.CC_NAMIBIA, AppText.cc_namibia, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fnamibia.png?alt=media&token=1f7602c7-9fe4-4185-8257-dac0209771e4"),
    CountryFlag(CountryConst.CC_NEPAL, AppText.cc_nepal, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fnepal.png?alt=media&token=ac4fab2f-3c6e-4821-85e5-0fefe678c74f"),
    CountryFlag(CountryConst.CC_NETHERLANDS, AppText.cc_netherlands, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fnetherlands.png?alt=media&token=4d5695ec-7a6a-4eb0-87bf-a485e55877cc"),
    CountryFlag(CountryConst.CC_NEW_ZEALAND, AppText.cc_new_zealand, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fnew_zealand.png?alt=media&token=e305e007-910b-4b55-a780-ae2a1433450b"),
    CountryFlag(CountryConst.CC_NICARAGUA, AppText.cc_nicaragua, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fnicaragua.png?alt=media&token=13b6a564-02cd-4691-a36f-072d62d7b92a"),
    CountryFlag(CountryConst.CC_NIGER, AppText.cc_niger, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fniger.png?alt=media&token=12d81680-d9d3-4f89-a148-4084303a9cf5"),
    CountryFlag(CountryConst.CC_NIGERIA, AppText.cc_nigeria, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fnigeria.png?alt=media&token=116ff0e8-400c-4cfa-adf2-7e232319c81e"),
    CountryFlag(CountryConst.CC_NORTH_MACEDONIA, AppText.cc_north_macedonia, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fnorth_macedonia.png?alt=media&token=ba33dc48-71d4-4e9f-8acc-6156a8b21ea6"),
    CountryFlag(CountryConst.CC_NORWAY, AppText.cc_norway, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fnorway.png?alt=media&token=71491f83-5d79-4fa5-af1e-78531462c436"),
    CountryFlag(CountryConst.CC_OMAN, AppText.cc_oman, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Foman.png?alt=media&token=4a73c15a-879d-4cec-97f0-46b41f493316"),
    CountryFlag(CountryConst.CC_PAKISTAN, AppText.cc_pakistan, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fpakistan.png?alt=media&token=dcbdb777-696d-4e9a-b356-a76c4e647787"),
    CountryFlag(CountryConst.CC_PANAMA, AppText.cc_panama, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fpanama.png?alt=media&token=6063bf70-5156-4b5d-ac93-a0dc8aeb2d7d"),
    CountryFlag(CountryConst.CC_PAPUA_NEW_GUINEA, AppText.cc_papua_new_guinea, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fpapua_new_guinea.png?alt=media&token=33e311d2-75d0-4dd3-a579-9549d8064aee"),
    CountryFlag(CountryConst.CC_PARAGUAY, AppText.cc_paraguay, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fparaguay.png?alt=media&token=706520fd-c7c0-4202-936a-8a2da7e3ba94"),
    CountryFlag(CountryConst.CC_PERU, AppText.cc_peru, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fperu.png?alt=media&token=d602ad6e-ff0d-43a8-b4d6-3c1069d269cd"),
    CountryFlag(CountryConst.CC_PHILIPPINES, AppText.cc_philippines, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fphilippines.png?alt=media&token=83884bff-8ad2-41e9-a528-5a580e031e28"),
    CountryFlag(CountryConst.CC_POLAND, AppText.cc_poland, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fpoland.png?alt=media&token=53eea62f-51eb-4c61-8eb3-9b2f62c30854"),
    CountryFlag(CountryConst.CC_PORTUGAL, AppText.cc_portugal, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fportugal.png?alt=media&token=20b21225-6f61-4b29-adc6-aca7677ea440"),
    CountryFlag(CountryConst.CC_QATAR, AppText.cc_qatar, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fqatar.png?alt=media&token=738c7370-3ae1-4ef8-98e6-1bb20d67baf4"),
    CountryFlag(CountryConst.CC_ROMANIA, AppText.cc_romania, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fromania.png?alt=media&token=8a48df6c-10f7-491c-ae65-7606b705d935"),
    CountryFlag(CountryConst.CC_RUSSIA, AppText.cc_russia, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Frussia.png?alt=media&token=e8bf8676-fbcc-43e0-ad0a-5682e5a97573"),
    CountryFlag(CountryConst.CC_RWANDA, AppText.cc_rwanda, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Frwanda.png?alt=media&token=19c21c73-b6b9-4562-aa98-d90b8ef798c8"),
    CountryFlag(CountryConst.CC_SAMOA, AppText.cc_samoa, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fsamoa.png?alt=media&token=dc3de021-8cf0-4f86-961a-497593b909e2"),
    CountryFlag(CountryConst.CC_SAN_MARINO, AppText.cc_san_marino, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fsan_marino.png?alt=media&token=cabfbf15-68b1-467a-bbe5-a7b2c0a23945"),
    CountryFlag(CountryConst.CC_SAUDI_ARABIA, AppText.cc_saudi_arabia, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fsaudi_arabia.png?alt=media&token=f336637e-6cc7-4913-aaaf-a51eeb2046ce"),
    CountryFlag(CountryConst.CC_SENEGAL, AppText.cc_senegal, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fsenegal.png?alt=media&token=3edfb18a-284b-44ec-897b-cce4536d2d09"),
    CountryFlag(CountryConst.CC_SERBIA, AppText.cc_serbia, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fserbia.png?alt=media&token=2c0f87b0-f976-4e56-b746-b81def5bfa08"),
    CountryFlag(CountryConst.CC_SEYCHELLES, AppText.cc_seychelles, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fseychelles.png?alt=media&token=0cd36a93-bb84-47a3-b2c7-46590e546552"),
    CountryFlag(CountryConst.CC_SIERRA_LEONE, AppText.cc_sierra_leone, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fsierra_leone.png?alt=media&token=55324a3f-3160-4d39-820c-8eadc73387a8"),
    CountryFlag(CountryConst.CC_SINGAPORE, AppText.cc_singapore, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fsingapore.png?alt=media&token=5928582a-15eb-43a8-902a-feedd72d3f8e"),
    CountryFlag(CountryConst.CC_SLOVAKIA, AppText.cc_slovakia, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fslovakia.png?alt=media&token=d8f5b089-ae88-4252-a6d7-63d567b0380d"),
    CountryFlag(CountryConst.CC_SLOVENIA, AppText.cc_slovenia, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fslovenia.png?alt=media&token=68793bb3-882d-4326-a90f-f1c37fad03e6"),
    CountryFlag(CountryConst.CC_SOLOMON_ISLANDS, AppText.cc_solomon_islands, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fsolomon_islands.png?alt=media&token=fd3f2b3d-c8d8-438e-a4b7-ff5885b6b976"),
    CountryFlag(CountryConst.CC_SOMALIA, AppText.cc_somalia, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fsomalia.png?alt=media&token=71b98993-9ba0-46f6-9f8f-74d5d1b57c9f"),
    CountryFlag(CountryConst.CC_SOUTH_AFRICA, AppText.cc_south_africa, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fsouth_africa.png?alt=media&token=66d8a26b-3575-4f4e-86b6-f61d48f028f6"),
    CountryFlag(CountryConst.CC_SOUTH_KOREA, AppText.cc_south_korea, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fsouth_korea.png?alt=media&token=07890b81-5fa6-4a5f-ab31-6cb3feab5e74"),
    CountryFlag(CountryConst.CC_SPAIN, AppText.cc_spain, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fspain.png?alt=media&token=8aa511fd-d90c-4db9-bae7-1daf8caf9a2d"),
    CountryFlag(CountryConst.CC_SRI_LANKA, AppText.cc_sri_lanka, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fsri_lanka.png?alt=media&token=11daf61c-b6d4-4d69-9a42-b0613a399159"),
    CountryFlag(CountryConst.CC_ST_KITTS_NEVIS, AppText.cc_st_kitts_nevis, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fsaint_kitts_and_nevis.png?alt=media&token=4824db87-48e7-4891-b5d4-52bdc0cbe509"),
    CountryFlag(CountryConst.CC_ST_LUCIA, AppText.cc_st_lucia, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fst_lucia.png?alt=media&token=bf33c156-07e4-42a7-8128-b7db65916857"),
    CountryFlag(CountryConst.CC_SUDAN, AppText.cc_sudan, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fsudan.png?alt=media&token=3c812e22-28d8-488b-bcbc-a996fcca7de4"),
    CountryFlag(CountryConst.CC_SURINAME, AppText.cc_suriname, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fsuriname.png?alt=media&token=29395b51-88a7-4994-9703-e88782f5936e"),
    CountryFlag(CountryConst.CC_SWEDEN, AppText.cc_sweden, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fsweden.png?alt=media&token=b91258e5-615b-485f-a9cc-d90145611f08"),
    CountryFlag(CountryConst.CC_SWITZERLAND, AppText.cc_switzerland, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fswitzerland.png?alt=media&token=0e6b9c30-0ff4-4b1e-b8e0-145c328c0149"),
    CountryFlag(CountryConst.CC_TAIWAN, AppText.cc_taiwan, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Ftaiwan.png?alt=media&token=a64fda17-5658-490e-9c8d-1b2f05c9964a"),
    CountryFlag(CountryConst.CC_TAJIKISTAN, AppText.cc_tajikistan, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Ftajikistan.png?alt=media&token=74d8f9db-3fa5-4fb3-b759-835d8d786a23"),
    CountryFlag(CountryConst.CC_TANZANIA, AppText.cc_tanzania, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Ftanzania.png?alt=media&token=0da69ef3-600c-413f-a121-73f429f1cb4d"),
    CountryFlag(CountryConst.CC_THAILAND, AppText.cc_thailand, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fthailand.png?alt=media&token=176c6500-42b7-46c4-bd63-3210b9efda9b"),
    CountryFlag(CountryConst.CC_TOGO, AppText.cc_togo, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Ftogo.png?alt=media&token=4cb55d0f-ce9d-4492-bc63-3d0c391e93c1"),
    CountryFlag(CountryConst.CC_TONGA, AppText.cc_tonga, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Ftonga.png?alt=media&token=2043405b-25d9-402f-af2d-95157526c3c2"),
    CountryFlag(CountryConst.CC_TRINIDAD_TOBAGO, AppText.cc_trinidad_and_tobago, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Ftrinidad_and_tobago.png?alt=media&token=e611bc19-e52e-4c46-ac0a-4744b06f86bc"),
    CountryFlag(CountryConst.CC_TUNISIA, AppText.cc_tunisia, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Ftunisia.png?alt=media&token=935c25ab-8c83-4c05-9208-d9b0601c7e94"),
    CountryFlag(CountryConst.CC_TURKMENISTAN, AppText.cc_turkmenistan, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fturkmenistan.png?alt=media&token=c5774e7b-f9cb-4684-a8fc-dcb4a3e59701"),
    CountryFlag(CountryConst.CC_TURKS_CAICOS_ISLANDS, AppText.cc_turks_and_caicos_islands, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fturks_and_caicos.png?alt=media&token=372ce38a-149f-4bee-9b90-a02a271820da"),
    CountryFlag(CountryConst.CC_TURKEY, AppText.cc_turkey, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fturkey.png?alt=media&token=648c4bad-7c5b-4cb3-9fbb-fb958aea848e"),
    CountryFlag(CountryConst.CC_UGANDA, AppText.cc_uganda, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fuganda.png?alt=media&token=eb517d55-6c13-4ace-b358-327910e96cbb"),
    CountryFlag(CountryConst.CC_UKRAINE, AppText.cc_ukraine, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fukraine.png?alt=media&token=69997070-3101-42a5-a1bf-3e4a9b55ee21"),
    CountryFlag(CountryConst.CC_UNITED_ARAB_EMIRATES, AppText.cc_united_arab_emirates, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Funited_arab_emirates.png?alt=media&token=5d0fd2ae-d2df-4529-8234-b2939d1986f4"),
    CountryFlag(CountryConst.CC_UNITED_KINGDOM, AppText.cc_united_kingdom, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Funited_kingdom.png?alt=media&token=21704334-c3c8-4549-9ff7-7aba5ea02835"),
    CountryFlag(CountryConst.CC_UNITED_STATES, AppText.cc_united_states, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Funited_states.png?alt=media&token=5299eaca-d83e-4598-9c59-bdd218f77ba5"),
    CountryFlag(CountryConst.CC_URUGUAY, AppText.cc_uruguay, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Furuguay.png?alt=media&token=b2513f5a-def0-4904-9550-f0294177ce14"),
    CountryFlag(CountryConst.CC_UZBEKISTAN, AppText.cc_uzbekistan, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fuzbekistan.png?alt=media&token=008f130e-2b84-40e2-a168-5a4e54e6033a"),
    CountryFlag(CountryConst.CC_VANUATU, AppText.cc_vanuatu, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fvanuatu.png?alt=media&token=c505d446-d5e7-4463-b60c-baaf8825abbf"),
    CountryFlag(CountryConst.CC_VATICAN_CITY, AppText.cc_vatican_city, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fvatican_city.png?alt=media&token=1c232a77-ff78-4444-ab66-61380efec968"),
    CountryFlag(CountryConst.CC_VENEZUELA, AppText.cc_venezuela, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fvenezuela.png?alt=media&token=4b781e34-ffc5-42bb-bc58-9ae4ad2c81af"),
    CountryFlag(CountryConst.CC_VIETNAM, AppText.cc_vietnam, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fvietnam.png?alt=media&token=23524ad1-7cc2-4e1e-bf58-bbde0419b414"),
    CountryFlag(CountryConst.CC_YEMEN, AppText.cc_yemen, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fyemen.png?alt=media&token=2b601765-4bad-4679-bd5b-9dca060d1b77"),
    CountryFlag(CountryConst.CC_ZAMBIA, AppText.cc_zambia, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fzambia.png?alt=media&token=67ae56f6-88af-4c48-8906-efaa627a8cdb"),
    CountryFlag(CountryConst.CC_ZIMBABWE, AppText.cc_zimbabwe, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Fzimbabwe.png?alt=media&token=6f7c3863-b866-4bdc-932d-9039a4ae1a56"),
    CountryFlag(CountryConst.CC_REST_OF_WORLD, AppText.cc_rest_of_world, "https://firebasestorage.googleapis.com/v0/b/example-eeaa5.appspot.com/o/countryflag%2Funited_states.png?alt=media&token=5299eaca-d83e-4598-9c59-bdd218f77ba5")
)
